# Conventions

## Directory structure
**Rationale:** Virtually all of our raw data is generated from samples gifted Aboriginal and Torres Strait Islander peoples, and they must retain access to and control over their samples and data.  

The directory structure for raw and processed data, and any identifiable data that relates to a single individual should be stored in a directory structure with the individuals unique identifier as the higher level directory.

In the event of a person requesting their data to be deleted, this should be possible by deleting the top level folder associated to their participant id.

Within the directory of an individual, the data should be organised by assay type (WGS, DNAme, RNA-seq), and then the data types for each assay. 

It is ok to create symbolic links to files and folders within an individuals directory using the `ln -s` command.   

**Directory structure:**
```
├── ID
  ├── readme.md
  ├── WGS
    ├── raw
    ├── aligned
  ├── DNAme
    ├── raw
    ├── aligned
  ├── RNA
    ├── raw
    ├── aligned
```

For example, the directory structure for individual with the id `BODLAXXRD` might look like this.    
```
├── data
    ├── BODLAXXRD
        ├── readme.md
        ├── WGS
          ├── raw
            ├── BODLAXXRD_wgs_unaligned_1.cram
          ├── aligned
            ├── BODLAXXRD_wgs_aligned.cram
          ├── processed
            ├── BODLAXXRD_wgs.vcf
        ├── DNAme
          ├── raw
            ├── BODLAXXRD_DNAme_unaligned.cram
          ├── aligned
            ├── BODLAXXRD_DNAme_aligned.cram
```

## File naming

Three principles for file names:  

- Machine readable  
- Human readable  
- Works well with default ordering  

**Machine readable**
- Regular expression and globbing friendly names
  - **Avoid spaces**, punctuation, accented characters, case sensitivity
  - Easy to compute on
- Deliberate use of delimiters. Use the underscore `_` or dashes `-` to separate elements in file names.
- NEVER USE SPACES. Many computer systems cannot handle spaces in file names, so NEVER use spaces!

**Human readable**
- File name contains information on the file content. Basically, make it easy to figure out what the file is based on the name.

**Default ordering**
Use names that will order by default using commands like `ls`.

For example, if you use the `YYYMMDD` date format, `ls` would chronologically order the files. 
```
20211122_my_sequences_R1.fastq.gz
20211122_my_sequences_R2.fastq.gz
20220126_my_sequences_R1.fastq.gz
20220126_my_sequences_R1.fastq.gz
```
Or for example, prefixing your scripts with a number would enable natural ordering:
```
01_run_fastqc.sh
02_map_wgbs.sh
03_postmap_wgbs.sh
04_plot_map_stats.R
```

## Date formats
Use the format `YYYYMMDD`. This enables easy date sorting of files. 

Use [ISO 8601 formatted dates](https://en.wikipedia.org/wiki/ISO_8601) where date and time values are ordered from the largest to smallest unit of time: year, month (or week) and day, minute, second.  These formats enable easy chronological sorting.  

For example, 5 Jan 2012 would be `20120105` 

## File compression
All data files should be compressed using the method described for the file type in the standards for that assay. 

## README files
Each folder created with a participant id should be initialised with a `REAMDME.md` file. This file should used to record any relevant specifics for this sample. This could include details such as anomalies observed in a FASTQC report, below expected alignment rates, outlier on clustering, etc.  
