# Whole genome sequencing

---

## Raw data

### CRAM

**File type:** [CRAM](https://samtools.github.io/hts-specs/CRAMv3.pdf)  
**Description:**  CRAM supports a wide
range of lossless and lossy sequence data preservation strategies enabling users to choose which data should be preserved. [CRAM is the genomics compression standard for GA4GH](https://www.ga4gh.org/cram/) \
**Compression:** Genozip  
**Permissions:** Category 1  
**Community access:** TBD  
**Identifiable:** Yes  
**Location:**  
**Notes:**

---

## Mapped data

### CRAM

**File type:** [CRAM](https://samtools.github.io/hts-specs/CRAMv3.pdf)  
**Description:**  CRAM supports a wide
range of lossless and lossy sequence data preservation strategies enabling users to choose which data should be preserved. [CRAM is the genomics compression standard for GA4GH](https://www.ga4gh.org/cram/) \
**Compression:** Genozip  
**Permissions:** Category 1  
**Access frequency:**  
**Community access:** TBD  
**Identifiable:** Yes  
**Location:** `/participant_id/wgs/processed/participant_id_.cram` 
**Notes:** When used with a reference genome, this exact reference genome file should be recorded.   

---

## Processed data

## VCF

**File type:** VCF  
**Description:**  [Variant Call Format](samtools.github.io/hts-specs/VCFv4.2.pdf)
**Compression:**  Genozip  
**Permissions:**  Category 1
**Access frequency:**  
**Community access:**  TBD
**Identifiable:**  Yes
**Location:**  `/participant_id/wgs/processed/participant_id_.vcf.genozip`
**Notes:**  
